services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: assur_auto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./action_elle_apk
      dockerfile: Dockerfile
    container_name: assur_auto_api
    restart: always
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=assur_auto;Username=admin;Password=admin123"
    ports:
      - "5000:5000"
      - "5001:5001"

  frontend:
    build:
      context: ./../action_elles_apk_front  
      dockerfile: Dockerfile  
    container_name: assur_auto_front
    restart: always
    ports:
      - "5173:5173"  
    depends_on:
      - api  # Le front dépend de l'API
    environment:
      - REACT_APP_API_URL=http://api:5000  # Variable d'environnement pour l'URL de l'API

volumes:
  postgres_data:
